### ISSUE TITLE
Disable autocomplete for input box

### ISSUE THREAD

**Issue by cheezgi** [rxi/lovebird#6]
It's *really* annoying when you're trying to search through history and you scroll through autocomplete options instead.

It's as simple (at least in chrome) as setting the `autocomplete` attribute of `#inputbox` to `off`. This attribute is [supported](https://www.w3.org/TR/html5/forms.html#attr-form-autocomplete) in HTML5, so it's mostly supported by modern browsers. I don't know if [Safari](http://stackoverflow.com/questions/22817801/how-to-disable-auto-fill-in-safari-7) is still an exception though, I'm not a web dev.

Also, this is an *awesome* project.

**Comment by rxi** [comment]
Which browser does this occur on for you? On both Firefox and Chrome everything works as expected for me unless I'm misunderstanding the issue. If there's some setting I need to enable let me know and I can give it another shot.

Alternatively if you make your suggested change yourself and this fixes things, feel free to make a pull request and I can merge it in if it doesn't change any other behaviour.

Thanks!

**Comment by cheezgi** [comment]
Hey, kinda late but whatever. It's happening to me on Chrome, I'll send a PR in just a minute.

**Comment by rxi** [comment]
Merged your pull request #7  -- thanks!
